### PR TITLE
Upgrade to OCaml 5.0

### PR DESCRIPTION
**Pull request by sim642**
This seems unrelated but Gobview doesn't compile for me at least:
```
File "gobview/goblint-http-server/api.ml", line 22, characters 14-18:
22 |   type body = unit [@@deriving yojson]
                   ^^^^
Error: Unbound value unit_of_yojson
```

On a side note, we really need to do #9 because jsoo-react 0.1 is now on opam, so we could avoid the pin and having to hack version bounds of some old jsoo-react fork ourselves.

### CODE REVIEW

**Comment by sim642** [comment]
The Gobview CI failure in https://github.com/goblint/analyzer/pull/1137 seems to suggest that it doesn't actually work for some reason.

**Review by michael-schwarz — APPROVED** [review]

**Comment by sim642** [comment]
I cherry-picked parts of this to `master` to fix the OCaml 5 compatibility, but not make it default yet.

Also the jsoo aliases didn't seem to work although jsoo's own `unix.js` uses them. Not sure what that's about, so I just duplicated the few functions for now.

**Comment by sim642** [comment]
Replaced by #52. Somehow it seems that the unix stubs changes aren't required anymore.
